### ISSUE TITLE
admission_details

### ISSUE THREAD

**Issue by wanghaisheng** [outcomesinsights/generalized_data_model#92]
does admission_details only contain inpatient admission and  emergency department encounters ?
what about outpatient ?

**Comment by markdanese** [comment]
It should contain records from any facility where the additional details are relevant.  For the most part, these will be inpatient hospitalizations.

**Comment by wanghaisheng** [comment]
how does you distinguish between facility and non-facility?

**Comment by markdanese** [comment]
Facilities bill using a UB04 form.  Typically these are the inpatient facility and outpatient facility files.  There are others too, like hospice, that are less commonly available.  These do not include physician bills, which are billed on the HCFA 1500 form.  (This is all for the United States, and other countries may do things differently, of course.)

**Comment by markdanese** [comment]
This slide deck might be helpful:  http://resdac.umn.edu/sites/resdac.umn.edu/files/Claims%20Data%20-%20Source%20and%20Processing%20(Slides).pdf

**Comment by wanghaisheng** [comment]
yes  it really quite different from china. right now i am trying to map our database(which combines data from his lis and pacs ) to your data model .
Institutional
˗Hospital Inpatient  
˗Hospital Outpatient
˗Skilled Nursing Care
˗Home Health Care
˗Hospice

Non-Institutional
˗Physician, Laboratory and Other Supplier Services
˗Durable Medical Equipment

**Comment by markdanese** [comment]
Your data should fit into our data model, but I am not familiar with how claims are created in China.  

For the most part, the start and stop dates go in the main files (like Contexts).  The admissions details file is really for additional information about the admission that isn't a condition/procedure/lab code.  It is really meta-data about the admission.  By and large, an admission is an overnight stay in a hospital, so the admissions details table is only going to be useful for that.  In the US, we can have some overnight hospital stays in the outpatient file, but that is because of "observation stays" where people are in the hospital simply to be observed.

**Comment by wanghaisheng** [comment]
we right now focus on EHR/EMR  instead of claim data.there is no public claim data we can research in China.

**Comment by markdanese** [comment]
closing.  can re-open if there are more questions.
